# Generated by Django 5.1.6 on 2025-03-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="main.jpg", upload_to="media/profile_pics/"
            ),
        ),
    ]
