# Generated by Django 5.1.6 on 2025-03-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="main.jpg", upload_to="profile_pics"),
        ),
    ]
